# Generated by Django 3.2.10 on 2021-12-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.AddField(
            model_name='modules',
            name='module_code',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='modules',
            name='module_time',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
