# Generated by Django 3.2.10 on 2021-12-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211214_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='name',
            field=models.TextField(default='module name'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_code',
            field=models.CharField(default='xxx0000', max_length=7),
        ),
    ]
